apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort       # Add this line
  selector:
    app: mern-server   # Assuming this is your selector
  ports:
    - protocol: TCP
      port: 5000       # Assuming these are your ports
      targetPort: 5000
      nodePort: 30001  # Your nodePort